#index:
#    path: /
#    controller: App\Controller\DefaultController::index


ControllerPassager :
  path: /passager
  controller:   App\Controller\ControllerPassager::controllerpassager


ControllerVoyage :
  path: /voyage
  controller:   App\Controller\ControllerVoyage::controllervoyage

ControllerDossier:
  path: /dossier
  controller: App\Controller\ControllerDossier::controllerdossier

ControllerVoyageParPassager:
  path: /parPassager
  controller: App\Controller\ControllerDossier::ControllerVoyageParPassager